USE customer_behavior;
SHOW TABLES;
SELECT COUNT(*) FROM customer;
SELECT * FROM customer LIMIT 10;
-- Q1 What is the total revenue generated by male vs female customer ?
SELECT gender,
       SUM(`purchase_amount_(usd)`) AS revenue
FROM customer
GROUP BY gender;
-- Q2 Which customers used a discount but still spend more than the average purchase ?
SELECT customer_id, `purchase_amount_(usd)` AS purchase_amount
FROM customer
WHERE discount_applied = 'Yes'
  AND `purchase_amount_(usd)` > (SELECT AVG(`purchase_amount_(usd)`) FROM customer)
ORDER BY `purchase_amount_(usd)` DESC;

-- Q3 Top 5 products with the highest average review ratings
SELECT item_purchased,
       AVG(review_rating) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5;

-- Q4 Compare average purchase amount between Standard and Express shipping
SELECT shipping_type,
       AVG(`purchase_amount_(usd)`) AS avg_purchase
FROM customer
WHERE shipping_type IN ('Standard','Express')
GROUP BY shipping_type;

-- Q5 Subscribers vs Non-subscribers: average spend + total revenue
SELECT subscription_status,
       AVG(`purchase_amount_(usd)`) AS avg_spend,
       SUM(`purchase_amount_(usd)`) AS total_revenue,
       COUNT(*) AS total_orders
FROM customer
GROUP BY subscription_status;

-- Q6 Top 5 products with highest % of purchases with discounts applied
SELECT item_purchased,
       COUNT(*) AS total_orders,
       SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) AS discounted_orders,
       100.0 * SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END) / COUNT(*) AS discount_pct
FROM customer
GROUP BY item_purchased
ORDER BY discount_pct DESC, total_orders DESC
LIMIT 5;

-- Q7 Segment customers (New/Returning/Loyal) by previous_purchases and count
SELECT
  CASE
    WHEN previous_purchases = 0 THEN 'New'
    WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
    ELSE 'Loyal'
  END AS segment,
  COUNT(*) AS customer_count
FROM customer
GROUP BY segment
ORDER BY customer_count DESC;

-- Q8 Top 3 most purchased products within each category
SELECT category, item_purchased, purchase_count
FROM (
  SELECT category,
         item_purchased,
         COUNT(*) AS purchase_count,
         DENSE_RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
  FROM customer
  GROUP BY category, item_purchased
) x
WHERE rnk <= 3
ORDER BY category, purchase_count DESC;

-- Q9 Repeat buyers (>5 previous purchases): are they likely to subscribe?
SELECT
  CASE WHEN previous_purchases > 5 THEN 'RepeatBuyer(>5)' ELSE 'NotRepeat(<=5)' END AS buyer_type,
  subscription_status,
  COUNT(*) AS customers
FROM customer
GROUP BY buyer_type, subscription_status
ORDER BY buyer_type, customers DESC;

-- Q10 Revenue contribution of each age group
SELECT age_group,
       SUM(`purchase_amount_(usd)`) AS revenue,
       COUNT(*) AS orders
FROM (
  SELECT
    CASE
      WHEN age < 20 THEN 'Under 20'
      WHEN age BETWEEN 20 AND 29 THEN '20-29'
      WHEN age BETWEEN 30 AND 39 THEN '30-39'
      WHEN age BETWEEN 40 AND 49 THEN '40-49'
      WHEN age BETWEEN 50 AND 59 THEN '50-59'
      ELSE '60+'
    END AS age_group,
    `purchase_amount_(usd)`
  FROM customer
) a
GROUP BY age_group
ORDER BY revenue DESC;

USE customer_behavior;
SELECT * FROM customer;

SELECT COUNT(*) AS total_rows
FROM customer;
